const LESSONS = [
{t:"打招呼 Greetings",w:[
["hello","你好","Hello! How are you?","你好！你好嗎？"],
["good morning","早安","Good morning, everyone.","大家早安。"],
["nice to meet you","很高興認識你","Nice to meet you, Tom.","很高興認識你，Tom。"],
["thank you","謝謝","Thank you very much.","非常謝謝你。"],
["goodbye","再見","Goodbye! See you tomorrow.","再見！明天見。"],
["please","請","Please sit down.","請坐。"]],
s:[["Hi, I'm Rick. Nice to meet you.","嗨，我是 Rick。很高興認識你。"],["How are you? I'm fine, thanks.","你好嗎？我很好，謝謝。"],["Good morning! Have a nice day.","早安！祝你有美好的一天。"]]},
{t:"自我介紹 Self-introduction",w:[
["name","名字","My name is Rick.","我的名字是 Rick。"],
["from","來自","I'm from Taiwan.","我來自台灣。"],
["live","住","I live in Taichung.","我住在台中。"],
["job","工作","What's your job?","你的工作是什麼？"],
["business","生意、事業","I have my own business.","我有自己的事業。"],
["hobby","嗜好","My hobby is pickleball.","我的嗜好是匹克球。"]],
s:[["I'm from Taiwan. I live in Taichung.","我來自台灣，住在台中。"],["I run a small business.","我經營一間小公司。"],["What do you do? I'm a designer.","你做什麼工作？我是設計師。"]]},
{t:"數字 Numbers 1–10",w:[
["one","一","I have one brother.","我有一個哥哥。"],
["two","二","Two coffees, please.","請給我兩杯咖啡。"],
["three","三","Table for three.","三位。"],
["five","五","It's five dollars.","五美元。"],
["seven","七","I get up at seven.","我七點起床。"],
["ten","十","Ten minutes, please.","請等十分鐘。"]],
s:[["Two tickets, please.","請給我兩張票。"],["A table for four, please.","請給我四人的桌子。"],["It costs ten dollars.","這要十美元。"]]},
{t:"時間 Time",w:[
["time","時間","What time is it?","現在幾點？"],
["o'clock","…點鐘","It's three o'clock.","現在三點。"],
["half","一半、半","It's half past six.","現在六點半。"],
["minute","分鐘","Wait a minute.","等一下。"],
["hour","小時","One hour, please.","請給我一小時。"],
["late","遲到、晚","Sorry, I'm late.","抱歉，我遲到了。"]],
s:[["What time is it now? It's 2:30.","現在幾點？兩點半。"],["The shop opens at nine.","這家店九點開。"],["I'm five minutes late. Sorry!","我遲到五分鐘，抱歉！"]]},
{t:"日期 Days & Dates",w:[
["today","今天","Today is Monday.","今天是星期一。"],
["tomorrow","明天","See you tomorrow.","明天見。"],
["yesterday","昨天","I arrived yesterday.","我昨天到的。"],
["weekend","週末","What do you do on the weekend?","你週末做什麼？"],
["week","週","I'm here for one week.","我在這裡待一週。"],
["month","月","Next month I go to Japan.","下個月我去日本。"]],
s:[["What day is it today? It's Friday.","今天星期幾？星期五。"],["I'm leaving on Sunday.","我星期天離開。"],["My birthday is in December.","我的生日在十二月。"]]},
{t:"禮貌用語 Polite phrases",w:[
["excuse me","不好意思","Excuse me, where is the toilet?","不好意思，廁所在哪？"],
["sorry","對不起","Sorry, I don't understand.","對不起，我不懂。"],
["you're welcome","不客氣","You're welcome!","不客氣！"],
["no problem","沒問題","No problem, take your time.","沒問題，慢慢來。"],
["of course","當然","Of course you can.","當然可以。"],
["help","幫忙","Can you help me?","你可以幫我嗎？"]],
s:[["Excuse me, can you help me?","不好意思，可以幫我嗎？"],["Sorry, can you say that again?","抱歉，可以再說一次嗎？"],["Thank you so much. You're welcome.","非常感謝。不客氣。"]]},
{t:"問句 Questions",w:[
["what","什麼","What is this?","這是什麼？"],
["where","哪裡","Where are you from?","你來自哪裡？"],
["when","什麼時候","When do you leave?","你什麼時候離開？"],
["how much","多少錢","How much is it?","這多少錢？"],
["who","誰","Who is he?","他是誰？"],
["why","為什麼","Why not?","為什麼不？"]],
s:[["Where is the station?","車站在哪裡？"],["How much is this bag?","這個包多少錢？"],["What does this mean?","這是什麼意思？"]]},
{t:"家人 Family",w:[
["family","家人","This is my family.","這是我的家人。"],
["parents","父母","My parents live in Taiwan.","我父母住在台灣。"],
["wife","太太","This is my wife.","這是我太太。"],
["brother","兄弟","I have one brother.","我有一個兄弟。"],
["sister","姊妹","My sister is a teacher.","我姊姊是老師。"],
["kid","小孩","Do you have kids?","你有小孩嗎？"]],
s:[["I have two brothers and one sister.","我有兩個兄弟和一個姊妹。"],["Do you have kids? No, not yet.","你有小孩嗎？還沒有。"],["My parents are retired.","我父母退休了。"]]},
{t:"食物 Food basics",w:[
["breakfast","早餐","I eat breakfast at eight.","我八點吃早餐。"],
["lunch","午餐","Let's have lunch.","我們去吃午餐吧。"],
["dinner","晚餐","Dinner is at seven.","晚餐在七點。"],
["rice","米飯","I like rice.","我喜歡吃飯。"],
["chicken","雞肉","Chicken or beef?","雞肉還是牛肉？"],
["delicious","好吃的","This is delicious!","這好好吃！"]],
s:[["I usually have rice for lunch.","我午餐通常吃飯。"],["What's for dinner tonight?","今晚晚餐吃什麼？"],["This chicken is delicious.","這雞肉很好吃。"]]},
{t:"飲料與咖啡 Drinks & café",w:[
["coffee","咖啡","A coffee, please.","請給我一杯咖啡。"],
["tea","茶","I like bubble tea.","我喜歡珍珠奶茶。"],
["water","水","Can I have some water?","可以給我一些水嗎？"],
["milk","牛奶","No milk, thanks.","不加牛奶，謝謝。"],
["sugar","糖","Less sugar, please.","請少糖。"],
["ice","冰","No ice, please.","請去冰。"]],
s:[["One latte, no sugar, please.","請給我一杯拿鐵，不加糖。"],["Hot or iced? Iced, please.","熱的還是冰的？冰的。"],["For here or to go? To go.","內用還是外帶？外帶。"]]},
{t:"家裡 At home",w:[
["home","家","I'm at home now.","我現在在家。"],
["room","房間","My room is small.","我的房間很小。"],
["kitchen","廚房","The kitchen is clean.","廚房很乾淨。"],
["bathroom","浴室","Where is the bathroom?","浴室在哪？"],
["bed","床","The bed is big.","床很大。"],
["door","門","Please close the door.","請關門。"]],
s:[["I work from home.","我在家工作。"],["The bathroom is on the left.","浴室在左邊。"],["Please open the window.","請開窗。"]]},
{t:"日常作息 Daily routine",w:[
["wake up","起床","I wake up at six.","我六點起床。"],
["work","工作","I work every day.","我每天工作。"],
["exercise","運動","I exercise in the morning.","我早上運動。"],
["busy","忙碌的","I'm busy today.","我今天很忙。"],
["free","有空的","Are you free tonight?","你今晚有空嗎？"],
["sleep","睡覺","I sleep at eleven.","我十一點睡覺。"]],
s:[["I wake up early and exercise.","我早起運動。"],["Are you free on Saturday?","你星期六有空嗎？"],["I'm too busy this week.","我這週太忙了。"]]},
{t:"天氣 Weather",w:[
["weather","天氣","How's the weather?","天氣如何？"],
["hot","熱的","It's very hot today.","今天很熱。"],
["cold","冷的","It's cold outside.","外面很冷。"],
["rain","雨、下雨","It's raining.","正在下雨。"],
["sunny","晴朗的","It's sunny today.","今天是晴天。"],
["umbrella","雨傘","Take an umbrella.","帶把傘。"]],
s:[["It's hot and sunny in Taiwan.","台灣又熱又晴朗。"],["Is it going to rain tomorrow?","明天會下雨嗎？"],["Bring a jacket. It's cold at night.","帶件外套，晚上很冷。"]]},
{t:"感覺 Feelings",w:[
["happy","開心的","I'm so happy.","我很開心。"],
["tired","累的","I'm tired today.","我今天很累。"],
["hungry","餓的","I'm hungry. Let's eat.","我餓了，吃飯吧。"],
["thirsty","渴的","I'm thirsty.","我口渴。"],
["excited","興奮的","I'm excited about the trip.","我對這趟旅行很興奮。"],
["fine","好的、還好","I'm fine, thanks.","我很好，謝謝。"]],
s:[["I'm tired. Let's take a break.","我累了，休息一下吧。"],["Are you hungry? A little.","你餓嗎？有一點。"],["I'm excited to see you!","見到你我很興奮！"]]},
{t:"機場報到 Airport check-in",w:[
["airport","機場","The airport is far.","機場很遠。"],
["flight","航班","My flight is at ten.","我的航班在十點。"],
["ticket","機票、票","Here is my ticket.","這是我的票。"],
["passport","護照","Here is my passport.","這是我的護照。"],
["window seat","靠窗座位","A window seat, please.","請給我靠窗座位。"],
["check in","報到","Where do I check in?","我要在哪裡報到？"]],
s:[["I'd like to check in, please.","我想要辦理報到。"],["Can I have a window seat?","可以給我靠窗的座位嗎？"],["Here's my passport and ticket.","這是我的護照和機票。"]]},
{t:"安檢與登機 Security & boarding",w:[
["gate","登機門","Which gate is it?","是哪個登機門？"],
["boarding pass","登機證","Show your boarding pass.","出示你的登機證。"],
["security","安檢","Security is this way.","安檢在這邊。"],
["liquid","液體","No liquids over 100 ml.","不能帶超過 100 毫升的液體。"],
["delay","延誤","The flight is delayed.","航班延誤了。"],
["board","登機","We board at 9:30.","我們九點半登機。"]],
s:[["Where is gate B12?","B12 登機門在哪？"],["Please take off your shoes.","請脫鞋。"],["Is the flight on time?","航班準時嗎？"]]},
{t:"飛機上 On the plane",w:[
["seat","座位","This is my seat.","這是我的座位。"],
["seat belt","安全帶","Fasten your seat belt.","繫好安全帶。"],
["blanket","毯子","Can I have a blanket?","可以給我毯子嗎？"],
["chicken or beef","雞肉還是牛肉","Chicken or beef? Beef, please.","雞肉還是牛肉？牛肉。"],
["headphones","耳機","Do you have headphones?","有耳機嗎？"],
["land","降落","We land at six.","我們六點降落。"]],
s:[["Excuse me, this is my seat.","不好意思，這是我的座位。"],["Can I have some water, please?","可以給我一些水嗎？"],["How long until we land?","還要多久降落？"]]},
{t:"入境 Immigration",w:[
["purpose","目的","What's the purpose of your visit?","你來訪的目的是什麼？"],
["vacation","度假","I'm here on vacation.","我來度假。"],
["stay","停留","How long will you stay?","你會停留多久？"],
["hotel","飯店","I'm staying at a hotel.","我住飯店。"],
["return","回去","My return flight is on Friday.","我回程航班在星期五。"],
["visit","拜訪、造訪","I'm visiting friends.","我來拜訪朋友。"]],
s:[["I'm here for sightseeing.","我來觀光。"],["I'll stay for five days.","我會待五天。"],["I'm staying at the Hilton Hotel.","我住在希爾頓飯店。"]]},
{t:"行李與海關 Baggage & customs",w:[
["luggage","行李","Where is my luggage?","我的行李在哪？"],
["suitcase","行李箱","My suitcase is black.","我的行李箱是黑色的。"],
["lost","遺失的","My bag is lost.","我的包不見了。"],
["declare","申報","Nothing to declare.","沒有要申報的。"],
["carry-on","隨身行李","This is my carry-on.","這是我的隨身行李。"],
["heavy","重的","My bag is too heavy.","我的包太重了。"]],
s:[["Where can I pick up my luggage?","我在哪裡領行李？"],["I have nothing to declare.","我沒有東西要申報。"],["My suitcase didn't arrive.","我的行李箱沒有到。"]]},
{t:"計程車 Taxi",w:[
["taxi","計程車","Let's take a taxi.","我們搭計程車吧。"],
["address","地址","Here is the address.","這是地址。"],
["meter","計費表","Please use the meter.","請跳表。"],
["stop","停","Stop here, please.","請在這裡停。"],
["change","零錢、找零","Keep the change.","不用找了。"],
["receipt","收據","Can I have a receipt?","可以給我收據嗎？"]],
s:[["To this hotel, please.","請到這間飯店。"],["How much to the airport?","到機場多少錢？"],["Can you stop here? Thanks.","可以在這裡停嗎？謝謝。"]]},
{t:"火車與捷運 Train & metro",w:[
["train","火車","The train is coming.","火車來了。"],
["subway","地鐵","Take the subway.","搭地鐵。"],
["station","車站","Which station is this?","這是哪一站？"],
["platform","月台","Go to platform 2.","去第二月台。"],
["transfer","轉乘","Transfer at Central.","在中央站轉乘。"],
["one-way","單程的","One-way ticket, please.","請給我單程票。"]],
s:[["Which line goes downtown?","哪條線到市中心？"],["Where do I transfer?","我在哪裡轉車？"],["Does this train stop at the airport?","這班車有停機場嗎？"]]},
{t:"飯店入住 Hotel check-in",w:[
["reservation","預訂","I have a reservation.","我有預訂。"],
["room key","房間鑰匙","Here is your room key.","這是你的房卡。"],
["floor","樓層","What floor is it?","在幾樓？"],
["elevator","電梯","The elevator is there.","電梯在那裡。"],
["breakfast included","含早餐","Is breakfast included?","有含早餐嗎？"],
["Wi-Fi","無線網路","What's the Wi-Fi password?","Wi-Fi 密碼是什麼？"]],
s:[["I have a reservation under Huang.","我用黃這個姓名預訂。"],["What time is breakfast?","早餐幾點？"],["Is Wi-Fi free?","Wi-Fi 免費嗎？"]]},
{t:"飯店房間 Hotel room",w:[
["towel","毛巾","I need more towels.","我需要更多毛巾。"],
["shower","淋浴","The shower is hot.","淋浴很燙。"],
["air conditioner","冷氣","Turn on the air conditioner.","打開冷氣。"],
["pillow","枕頭","One more pillow, please.","請再給我一個枕頭。"],
["clean","乾淨的","The room is clean.","房間很乾淨。"],
["quiet","安靜的","I want a quiet room.","我想要安靜的房間。"]],
s:[["Can I have an extra pillow?","可以多給我一個枕頭嗎？"],["The air conditioner doesn't work.","冷氣壞了。"],["Could you clean my room, please?","可以幫我打掃房間嗎？"]]},
{t:"飯店問題 Hotel problems",w:[
["problem","問題","There is a problem.","有個問題。"],
["broken","壞掉的","The TV is broken.","電視壞了。"],
["noisy","吵鬧的","The room is noisy.","房間很吵。"],
["hot water","熱水","There's no hot water.","沒有熱水。"],
["change","更換","Can I change rooms?","可以換房間嗎？"],
["fix","修理","Can you fix it?","你可以修好它嗎？"]],
s:[["There's no hot water in my room.","我房間沒有熱水。"],["The room is too noisy. Can I change?","房間太吵了，可以換嗎？"],["Can someone come and fix it?","可以派人來修嗎？"]]},
{t:"飯店服務 Hotel services",w:[
["front desk","櫃台","Call the front desk.","打給櫃台。"],
["wake-up call","晨喚服務","A wake-up call at six, please.","請六點叫我起床。"],
["laundry","洗衣","Do you have laundry service?","有洗衣服務嗎？"],
["safe","保險箱","Put it in the safe.","放進保險箱。"],
["gym","健身房","Is there a gym?","有健身房嗎？"],
["pool","游泳池","The pool is on the roof.","泳池在屋頂。"]],
s:[["Can I get a wake-up call at 6?","可以六點叫我起床嗎？"],["Where is the gym?","健身房在哪？"],["Can you keep my luggage?","可以幫我寄放行李嗎？"]]},
{t:"退房 Check-out",w:[
["check out","退房","I'd like to check out.","我要退房。"],
["bill","帳單","Here's your bill.","這是你的帳單。"],
["credit card","信用卡","I'll pay by credit card.","我用信用卡付。"],
["cash","現金","Cash, please.","現金。"],
["deposit","押金","You get your deposit back.","你會拿回押金。"],
["mistake","錯誤","There's a mistake here.","這裡有錯。"]],
s:[["I'd like to check out, room 812.","我要退房，812 號房。"],["Can I pay by card?","可以刷卡嗎？"],["I think there's a mistake on the bill.","我覺得帳單有錯。"]]},
{t:"問路 Asking directions",w:[
["left","左邊","Turn left.","左轉。"],
["right","右邊","Turn right.","右轉。"],
["straight","直走","Go straight.","直走。"],
["near","近的","Is it near here?","離這裡近嗎？"],
["far","遠的","It's not far.","不遠。"],
["map","地圖","Can you show me on the map?","可以在地圖上指給我看嗎？"]],
s:[["How do I get to the station?","我要怎麼去車站？"],["Go straight, then turn left.","直走，然後左轉。"],["Is it far? No, five minutes on foot.","遠嗎？不遠，走路五分鐘。"]]},
{t:"市區地點 Places in town",w:[
["bank","銀行","The bank is closed.","銀行關了。"],
["supermarket","超市","Let's go to the supermarket.","我們去超市吧。"],
["pharmacy","藥局","Is there a pharmacy nearby?","附近有藥局嗎？"],
["park","公園","The park is beautiful.","公園很美。"],
["museum","博物館","The museum opens at ten.","博物館十點開。"],
["restroom","洗手間","Where is the restroom?","洗手間在哪？"]],
s:[["Is there a supermarket near here?","這附近有超市嗎？"],["Where's the nearest restroom?","最近的洗手間在哪？"],["The park is next to the museum.","公園在博物館旁邊。"]]},
{t:"餐廳訂位 Restaurant reservation",w:[
["restaurant","餐廳","This restaurant is popular.","這家餐廳很受歡迎。"],
["book","預訂","I'd like to book a table.","我想訂位。"],
["table","桌子、桌位","A table for two.","兩位的桌子。"],
["tonight","今晚","For tonight at seven.","今晚七點。"],
["wait","等待","How long is the wait?","要等多久？"],
["full","客滿的","We're full tonight.","我們今晚客滿。"]],
s:[["I'd like a table for two at seven.","我想要七點兩位的桌子。"],["Do I need a reservation?","需要訂位嗎？"],["How long do we have to wait?","我們要等多久？"]]},
{t:"點餐 Ordering",w:[
["menu","菜單","Can I see the menu?","可以看菜單嗎？"],
["order","點餐","Are you ready to order?","準備好點餐了嗎？"],
["recommend","推薦","What do you recommend?","你推薦什麼？"],
["same","一樣的","I'll have the same.","我要一樣的。"],
["spicy","辣的","Is it spicy?","會辣嗎？"],
["set meal","套餐","The set meal is cheaper.","套餐比較便宜。"]],
s:[["Can I have the menu, please?","可以給我菜單嗎？"],["I'll have the chicken, please.","我要雞肉。"],["What do you recommend? The steak.","你推薦什麼？牛排。"]]},
{t:"菜單單字 Menu words",w:[
["beef","牛肉","Beef noodles, please.","請給我牛肉麵。"],
["pork","豬肉","No pork for me.","我不吃豬肉。"],
["fish","魚","The fish is fresh.","魚很新鮮。"],
["vegetable","蔬菜","More vegetables, please.","請多一點蔬菜。"],
["soup","湯","The soup is hot.","湯很燙。"],
["dessert","甜點","Do you want dessert?","要甜點嗎？"]],
s:[["I'd like the fish with vegetables.","我想要魚配蔬菜。"],["Does it come with soup?","有附湯嗎？"],["What desserts do you have?","你們有什麼甜點？"]]},
{t:"特殊需求 Special requests",w:[
["allergic","過敏的","I'm allergic to nuts.","我對堅果過敏。"],
["vegetarian","素食者","I'm vegetarian.","我吃素。"],
["without","不加、沒有","Without onions, please.","請不加洋蔥。"],
["less","少一點","Less salt, please.","請少鹽。"],
["well done","全熟","Well done, please.","請全熟。"],
["medium","五分熟","Medium, please.","五分熟。"]],
s:[["I'm allergic to seafood.","我對海鮮過敏。"],["Can you make it without garlic?","可以不加大蒜嗎？"],["How would you like your steak? Medium.","牛排要幾分熟？五分。"]]},
{t:"結帳 Paying the bill",w:[
["check","帳單（美式）","Check, please.","請結帳。"],
["tip","小費","Is the tip included?","有含小費嗎？"],
["separately","分開地","Can we pay separately?","我們可以分開付嗎？"],
["total","總計","The total is fifty dollars.","總共五十美元。"],
["card","卡片","Card or cash?","刷卡還是現金？"],
["service charge","服務費","There's a 10% service charge.","有百分之十的服務費。"]],
s:[["Can we have the check, please?","可以結帳嗎？"],["Is service included?","有含服務費嗎？"],["We'd like to pay separately.","我們想分開付。"]]},
{t:"速食店 Fast food",w:[
["burger","漢堡","A cheeseburger, please.","請給我一個起司漢堡。"],
["fries","薯條","Large fries, please.","請給我大薯。"],
["combo","套餐","Number two combo.","二號餐。"],
["large","大的","A large coke.","大杯可樂。"],
["to go","外帶","To go, please.","外帶。"],
["ketchup","番茄醬","More ketchup, please.","請多給番茄醬。"]],
s:[["Can I get a number one combo?","我可以點一號餐嗎？"],["For here or to go? For here.","內用還是外帶？內用。"],["Can I have extra ketchup?","可以多給我番茄醬嗎？"]]},
{t:"市場與小吃 Market & street food",w:[
["market","市場","The night market is fun.","夜市很好玩。"],
["try","嘗試","Can I try it?","我可以試試嗎？"],
["fresh","新鮮的","The fruit is fresh.","水果很新鮮。"],
["piece","一片、一塊","One piece, please.","請給我一片。"],
["sweet","甜的","It's too sweet.","太甜了。"],
["local","當地的","What's a local dish?","有什麼當地菜？"]],
s:[["What is this? Can I try one?","這是什麼？可以試一個嗎？"],["How much for one piece?","一片多少錢？"],["What's the most popular local food?","最受歡迎的當地食物是什麼？"]]},
{t:"買衣服 Clothes",w:[
["shirt","襯衫","I like this shirt.","我喜歡這件襯衫。"],
["pants","褲子","These pants are long.","這條褲子很長。"],
["shoes","鞋子","Do you have these shoes in 42?","這雙鞋有 42 號嗎？"],
["jacket","外套","This jacket is warm.","這件外套很暖。"],
["try on","試穿","Can I try it on?","我可以試穿嗎？"],
["fitting room","試衣間","Where is the fitting room?","試衣間在哪？"]],
s:[["Can I try this on?","我可以試穿這件嗎？"],["Do you have this in a different color?","這件有其他顏色嗎？"],["The fitting room is over there.","試衣間在那邊。"]]},
{t:"尺寸與顏色 Sizes & colors",w:[
["size","尺寸","What size are you?","你穿什麼尺寸？"],
["small","小號","Small, please.","小號。"],
["bigger","更大的","Do you have a bigger one?","有更大的嗎？"],
["black","黑色","In black, please.","黑色的。"],
["white","白色","The white one is nice.","白色的很好看。"],
["blue","藍色","I like the blue one.","我喜歡藍色的。"]],
s:[["Do you have this in a medium?","這件有中號嗎？"],["It's too small. Do you have a larger size?","太小了，有大一號的嗎？"],["I'll take the black one.","我要黑色的。"]]},
{t:"價格與殺價 Prices & bargaining",w:[
["price","價格","What's the price?","價格是多少？"],
["expensive","貴的","That's too expensive.","太貴了。"],
["cheap","便宜的","This one is cheap.","這個很便宜。"],
["discount","折扣","Is there a discount?","有折扣嗎？"],
["sale","特價","It's on sale.","它在特價。"],
["best price","最低價","What's your best price?","最低多少？"]],
s:[["How much is this? Twenty dollars.","這多少錢？二十美元。"],["That's too expensive. Can you give me a discount?","太貴了，可以打折嗎？"],["If I buy two, is it cheaper?","買兩個會便宜嗎？"]]},
{t:"付款與退貨 Paying & returns",w:[
["pay","付款","Where do I pay?","我在哪裡付款？"],
["bag","袋子","Do you need a bag?","需要袋子嗎？"],
["refund","退款","Can I get a refund?","可以退款嗎？"],
["exchange","換貨","I'd like to exchange this.","我想換貨。"],
["wrong","錯誤的","This is the wrong size.","這尺寸錯了。"],
["keep","保留","Keep the receipt.","留著收據。"]],
s:[["Can I pay by credit card?","可以刷信用卡嗎？"],["I'd like to return this. Here's the receipt.","我想退這個，這是收據。"],["Can I exchange it for a larger one?","可以換大一號的嗎？"]]},
{t:"紀念品 Souvenirs",w:[
["souvenir","紀念品","I want to buy souvenirs.","我想買紀念品。"],
["gift","禮物","It's a gift for my friend.","這是給朋友的禮物。"],
["wrap","包裝","Can you wrap it?","可以幫我包裝嗎？"],
["handmade","手工的","It's handmade.","這是手工的。"],
["popular","受歡迎的","This one is very popular.","這個很受歡迎。"],
["postcard","明信片","Two postcards, please.","請給我兩張明信片。"]],
s:[["What's a good souvenir from here?","這裡有什麼好的紀念品？"],["Can you gift-wrap this, please?","可以幫我包成禮物嗎？"],["Is this made here?","這是這裡做的嗎？"]]},
{t:"藥局 Pharmacy",w:[
["medicine","藥","I need some medicine.","我需要一些藥。"],
["headache","頭痛","I have a headache.","我頭痛。"],
["cold","感冒","I have a cold.","我感冒了。"],
["painkiller","止痛藥","Do you have painkillers?","有止痛藥嗎？"],
["band-aid","OK 繃","I need a band-aid.","我需要 OK 繃。"],
["twice a day","一天兩次","Take it twice a day.","一天吃兩次。"]],
s:[["Do you have something for a headache?","有治頭痛的藥嗎？"],["How often should I take it?","我要多久吃一次？"],["I need something for a sore throat.","我需要治喉嚨痛的東西。"]]},
{t:"便利商店 Convenience store",w:[
["snack","零食","I want a snack.","我想吃零食。"],
["bottle","瓶","A bottle of water.","一瓶水。"],
["heat up","加熱","Can you heat it up?","可以幫我加熱嗎？"],
["plastic bag","塑膠袋","No plastic bag, thanks.","不用塑膠袋，謝謝。"],
["ATM","提款機","Is there an ATM here?","這裡有提款機嗎？"],
["open 24 hours","24 小時營業","It's open 24 hours.","它 24 小時營業。"]],
s:[["Can you heat this up, please?","可以幫我加熱嗎？"],["Do you sell SIM cards?","你們有賣 SIM 卡嗎？"],["Is there an ATM nearby?","附近有提款機嗎？"]]},
{t:"觀光與門票 Sightseeing & tickets",w:[
["sightseeing","觀光","Let's go sightseeing.","我們去觀光吧。"],
["ticket office","售票處","The ticket office is closed.","售票處關了。"],
["adult","成人","Two adults, please.","兩張成人票。"],
["student","學生","Is there a student discount?","有學生優惠嗎？"],
["open","開放的、營業的","Is it open today?","今天有開嗎？"],
["closed","關閉的","It's closed on Mondays.","星期一休館。"]],
s:[["Two adult tickets, please.","請給我兩張成人票。"],["What time does it close?","幾點關門？"],["Is the museum open on Sunday?","博物館星期天有開嗎？"]]},
{t:"導覽 Museum & tours",w:[
["tour","導覽、旅行團","Is there a tour in English?","有英文導覽嗎？"],
["guide","導遊","Our guide is friendly.","我們的導遊很友善。"],
["start","開始","The tour starts at ten.","導覽十點開始。"],
["last","持續","How long does it last?","會持續多久？"],
["famous","有名的","This temple is famous.","這座廟很有名。"],
["history","歷史","I like history.","我喜歡歷史。"]],
s:[["When does the next tour start?","下一場導覽幾點開始？"],["How long is the tour? About two hours.","導覽多長？大約兩小時。"],["Is there an audio guide?","有語音導覽嗎？"]]},
{t:"拍照 Photos",w:[
["photo","照片","Can I take a photo?","我可以拍照嗎？"],
["take a picture","拍照","Could you take a picture of us?","可以幫我們拍張照嗎？"],
["camera","相機","My camera is new.","我的相機是新的。"],
["smile","微笑","Smile!","笑一個！"],
["allowed","允許的","Photos are not allowed.","不允許拍照。"],
["beautiful","美麗的","What a beautiful view!","多美的景色！"]],
s:[["Could you take a picture of us, please?","可以幫我們拍張照嗎？"],["Is it okay to take photos here?","這裡可以拍照嗎？"],["One more, please. Say cheese!","再一張，笑一個！"]]},
{t:"緊急狀況 Emergencies",w:[
["help!","救命！","Help! Please call the police.","救命！請叫警察。"],
["police","警察","Where is the police station?","警察局在哪？"],
["lost","迷路的、遺失的","I'm lost.","我迷路了。"],
["stolen","被偷的","My wallet was stolen.","我的皮夾被偷了。"],
["embassy","大使館","Call the embassy.","打給大使館。"],
["emergency","緊急狀況","It's an emergency.","這是緊急狀況。"]],
s:[["I lost my passport. What should I do?","我護照弄丟了，該怎麼辦？"],["Someone stole my phone.","有人偷了我的手機。"],["Please call an ambulance.","請叫救護車。"]]},
{t:"看醫生 Doctor & sick",w:[
["sick","生病的","I feel sick.","我覺得不舒服。"],
["doctor","醫生","I need a doctor.","我需要醫生。"],
["hurt","痛、受傷","My stomach hurts.","我肚子痛。"],
["fever","發燒","I have a fever.","我發燒了。"],
["hospital","醫院","Where is the hospital?","醫院在哪？"],
["insurance","保險","I have travel insurance.","我有旅遊保險。"]],
s:[["I don't feel well. I need a doctor.","我不舒服，需要看醫生。"],["Where does it hurt? Here.","哪裡痛？這裡。"],["Do you accept travel insurance?","你們接受旅遊保險嗎？"]]},
{t:"手機與網路 Phone & Wi-Fi",w:[
["phone","手機","My phone is dead.","我手機沒電了。"],
["charge","充電","Can I charge my phone here?","我可以在這裡充電嗎？"],
["password","密碼","What's the password?","密碼是什麼？"],
["SIM card","SIM 卡","I need a SIM card.","我需要 SIM 卡。"],
["signal","訊號","There's no signal.","沒有訊號。"],
["data","流量","How much data is it?","有多少流量？"]],
s:[["Do you have free Wi-Fi?","有免費 Wi-Fi 嗎？"],["Where can I buy a SIM card?","我在哪裡可以買 SIM 卡？"],["Can I use your charger?","可以借用你的充電器嗎？"]]},
{t:"換錢 Bank & money",w:[
["exchange","兌換","Where can I exchange money?","我在哪裡可以換錢？"],
["rate","匯率","What's the rate today?","今天匯率多少？"],
["dollar","美元","One hundred dollars.","一百美元。"],
["coin","硬幣","I have no coins.","我沒有硬幣。"],
["withdraw","提款","I want to withdraw money.","我想提款。"],
["fee","手續費","Is there a fee?","有手續費嗎？"]],
s:[["I'd like to exchange 10,000 NT dollars.","我想換一萬台幣。"],["What's the exchange rate?","匯率是多少？"],["Can I withdraw money with this card?","我可以用這張卡提款嗎？"]]},
{t:"閒聊 Small talk",w:[
["first time","第一次","It's my first time here.","這是我第一次來這裡。"],
["trip","旅行","How's your trip?","旅行如何？"],
["enjoy","享受","I'm enjoying it.","我很享受。"],
["long","長的","It's a long flight.","飛行時間很長。"],
["really","真的","Really? That's great!","真的嗎？太棒了！"],
["favorite","最喜歡的","What's your favorite food?","你最喜歡的食物是什麼？"]],
s:[["Is this your first time in Taiwan?","這是你第一次來台灣嗎？"],["How long are you staying? One week.","你待多久？一週。"],["Do you like it here? I love it.","你喜歡這裡嗎？我很喜歡。"]]},
{t:"興趣 Hobbies",w:[
["sport","運動","What sports do you like?","你喜歡什麼運動？"],
["play","打、玩","I play pickleball.","我打匹克球。"],
["music","音樂","I like music.","我喜歡音樂。"],
["movie","電影","Let's watch a movie.","我們看電影吧。"],
["travel","旅行","I love to travel.","我喜歡旅行。"],
["cook","烹飪","I can cook.","我會做飯。"]],
s:[["What do you do in your free time?","你有空時做什麼？"],["I play pickleball twice a week.","我一週打兩次匹克球。"],["Do you like movies? Yes, action movies.","你喜歡電影嗎？喜歡，動作片。"]]},
{t:"邀請 Inviting",w:[
["join","加入","Want to join us?","要加入我們嗎？"],
["together","一起","Let's eat together.","我們一起吃飯吧。"],
["drink","喝、飲料","Let's get a drink.","我們去喝一杯吧。"],
["maybe","也許","Maybe next time.","也許下次。"],
["sure","當然、好啊","Sure, sounds good.","好啊，聽起來不錯。"],
["plan","計畫","Do you have plans tonight?","你今晚有計畫嗎？"]],
s:[["Would you like to have dinner with us?","你想跟我們一起吃晚餐嗎？"],["Sure! What time? Seven is good.","好啊！幾點？七點可以。"],["Sorry, I can't tonight. Maybe tomorrow?","抱歉今晚不行，明天可以嗎？"]]},
{t:"稱讚與感謝 Compliments & thanks",w:[
["great","很棒的","That's great!","太棒了！"],
["kind","親切的","You're very kind.","你人真好。"],
["nice","好的、好看的","Nice shirt!","襯衫很好看！"],
["appreciate","感激","I appreciate it.","我很感激。"],
["welcome","歡迎","Welcome to Taiwan!","歡迎來台灣！"],
["wonderful","美好的","We had a wonderful time.","我們過得很開心。"]],
s:[["Thank you for your help. I appreciate it.","謝謝你的幫忙，我很感激。"],["You speak English very well!","你英文說得很好！"],["The food was wonderful.","食物很棒。"]]},
{t:"道別 Saying goodbye",w:[
["leave","離開","I leave tomorrow.","我明天離開。"],
["see you","再見","See you next time.","下次見。"],
["keep in touch","保持聯絡","Let's keep in touch.","我們保持聯絡。"],
["safe","安全的","Have a safe trip.","一路平安。"],
["miss","想念","I'll miss you.","我會想你。"],
["again","再、又","Come again soon!","快再來！"]],
s:[["It was nice meeting you.","很高興認識你。"],["Have a safe flight! Thanks, you too.","一路順風！謝謝，你也是。"],["Let's keep in touch on Instagram.","我們在 Instagram 保持聯絡吧。"]]},
{t:"介紹台灣 Talking about Taiwan",w:[
["island","島嶼","Taiwan is an island.","台灣是個島。"],
["night market","夜市","You must try the night market.","你一定要去夜市。"],
["mountain","山","Taiwan has many mountains.","台灣有很多山。"],
["friendly","友善的","People here are friendly.","這裡的人很友善。"],
["convenient","方便的","Taipei is very convenient.","台北很方便。"],
["recommend","推薦","I recommend Taichung.","我推薦台中。"]],
s:[["Taiwan is famous for bubble tea.","台灣以珍珠奶茶聞名。"],["You should visit Sun Moon Lake.","你應該去日月潭。"],["The night markets are the best part.","夜市是最棒的部分。"]]},
{t:"總複習 Trip review",w:[
["remember","記得","I remember this place.","我記得這個地方。"],
["learn","學習","I learn English every day.","我每天學英文。"],
["practice","練習","Practice makes perfect.","熟能生巧。"],
["speak","說","I can speak a little English.","我會說一點英文。"],
["understand","理解","Now I understand.","現在我懂了。"],
["confident","有自信的","I feel more confident.","我覺得更有自信了。"]],
s:[["I've learned a lot this month.","我這個月學了很多。"],["I can order food and ask for directions now.","我現在會點餐和問路了。"],["Every day, a little better.","每天進步一點點。"]]}
];
